name: ai-portfolio
channels:
  - defaults
dependencies:
  - asttokens=3.0.0
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - ipykernel=6.30.1
  - ipython=8.15.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.9.25
  - python-dateutil=2.9.0post0
  - pywin32=311
  - pyzmq=27.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - pandas==2.3.3
      - pillow==11.3.0
      - pyparsing==3.2.5
      - pytz==2025.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - tzdata==2025.2
